name: terraform plan

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "."

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5
          terraform_wrapper: true
      
      - name: terraform init
        run: |
          terraform init

      - name: terraform validate
        run: |
          terraform validate
      
      - name: terraform plan
        run: |
          terraform plan -var-file=vars.tfvars -out=tfplan

          
